# Generated by Django 3.0.4 on 2020-04-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicCheckup',
            new_name='BasicChecku',
        ),
    ]
